### PR TITLE
fix: reload tab after blocking and prevent duplicate blocking

### LINKED ISSUE #29: Fixes: adding websites to the blocked list from pop-up
**Fixes to be made**
- Adding a blocked website through the pop-up should trigger a page reload if the URL matches the URL on the current tab
- User should not be able to add the same website more than once on the block list

### PR DESCRIPTION
**Pull request by Riri202**
Resolves #29 

- Ensures user cannot add a website to the block list more than once
- Page reload is triggered after blocking a website if the URL matches the URL on the current tab.

### CODE REVIEW

File: src/popup.tsx [hunk 1]
```diff
@@ -11,35 +11,49 @@ import { Storage } from "@plasmohq/storage"
...
-    const [tab] = await chrome.tabs.query(queryInfo)
-    setCurrentUrl(new URL(tab.url).hostname)
+  const reloadCurrentPage = async () => {
+    const urlToBeBlocked = extractHostname(currentUrl)
+    const currentTabUrl = await getCurrentTabUrl()
+    if (urlToBeBlocked === currentTabUrl) {
+      chrome.tabs.reload()
+    }
+    window.close()
+  }
```
Comment (DotCampus-Admin) [inline src/popup.tsx:45]: ❤️

**Review by DotCampus-Admin — APPROVED** [review]
LGTM! Thanks @Riri202

**Review by iamstarcode — APPROVED** [review]
Looks good to me. Nice work mam.
